import { useEffect, useState } from "react";
import "./OwnerPage.css";

interface KeyRecord {
  duration: string; generated_by: number | null; generated_at: string;
  disabled: boolean; claimed_by_discord: number | null;
  username: string | null; password_hash: string | null;
  hwid: string | null; registered_at: string | null;
}
type Tab = "keys" | "genkey" | "download" | "analytics" | "danger";

function Spoiler({ value }: { value: string }) {
  const [show, setShow] = useState(false);
  const [copied, setCopied] = useState(false);
  const copy = (e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard.writeText(value).then(() => { setCopied(true); setTimeout(() => setCopied(false), 1500); });
  };
  return (
    <span className="spoiler-wrap">
      <span className={`spoiler ${show ? "revealed" : ""}`} onClick={() => setShow(v => !v)}>{value}</span>
      {show && (
        <button className="spoiler-copy" onClick={copy} title={copied ? "Copied" : "Copy"}>
          {copied
            ? <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>
            : <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>}
        </button>
      )}
    </span>
  );
}

function Confirm({ msg, onYes, onNo }: { msg: string; onYes: () => void; onNo: () => void }) {
  return (
    <div className="modal-overlay" onClick={onNo}>
      <div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: 360 }}>
        <p className="modal-title" style={{ marginBottom: 8 }}>Confirm</p>
        <p className="modal-sub">{msg}</p>
        <div style={{ display: "flex", gap: 10 }}>
          <button className="btn btn-danger" style={{ flex: 1 }} onClick={onYes}>Confirm</button>
          <button className="btn btn-ghost" style={{ flex: 1 }} onClick={onNo}>Cancel</button>
        </div>
      </div>
    </div>
  );
}

function EditKeyModal({ keyId, rec, onClose, onSave }: {
  keyId: string; rec: KeyRecord; onClose: () => void;
  onSave: (k: string, u: Partial<KeyRecord>) => void;
}) {
  const [duration, setDuration] = useState(rec.duration);
  const [disabled, setDisabled] = useState(rec.disabled);
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>
        <p className="modal-title">Edit Key</p>
        <p className="owner-key-id">{keyId}</p>
        <div className="form-group">
          <label className="form-label">Duration</label>
          <input className="form-input" value={duration} onChange={e => setDuration(e.target.value)} />
        </div>
        <label style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20, fontSize: 13, color: "var(--gray-400)", cursor: "pointer" }}>
          <input type="checkbox" checked={disabled} onChange={e => setDisabled(e.target.checked)} style={{ accentColor: "white" }} />
          Disabled
        </label>
        <div style={{ display: "flex", gap: 10 }}>
          <button className="btn btn-primary" style={{ flex: 1 }} onClick={() => { onSave(keyId, { duration, disabled }); onClose(); }}>Save</button>
          <button className="btn btn-ghost" style={{ flex: 1 }} onClick={onClose}>Cancel</button>
        </div>
      </div>
    </div>
  );
}

function KeyViewModal({ keyId, rec, onClose }: { keyId: string; rec: KeyRecord; onClose: () => void }) {
  const fmt = (v: string | null) => v || "—";
  const fmtDate = (v: string | null) => v ? new Date(v).toLocaleString() : "—";
  const rows: [string, React.ReactNode][] = [
    ["Key", <code style={{ fontFamily: "monospace", fontSize: 12, wordBreak: "break-all" }}>{keyId}</code>],
    ["Duration", fmt(rec.duration)],
    ["Status", <span className={`tag ${rec.disabled ? "tag-red" : "tag-white"}`}>{rec.disabled ? "Disabled" : "Active"}</span>],
    ["Generated At", fmtDate(rec.generated_at)],
    ["Generated By", rec.generated_by ? `Discord ID: ${rec.generated_by}` : "—"],
    ["Claimed By", rec.claimed_by_discord ? `Discord ID: ${rec.claimed_by_discord}` : "Unclaimed"],
    ["Username", fmt(rec.username)],
    ["Password Hash", rec.password_hash ? <Spoiler value={rec.password_hash} /> : "—"],
    ["HWID", rec.hwid ? <Spoiler value={rec.hwid} /> : <span className="tag tag-dim">Unbound</span>],
    ["Registered At", fmtDate(rec.registered_at)],
  ];
  return (
    <div className="modal-overlay" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: 520, maxHeight: "80vh", overflowY: "auto" }}>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 }}>
          <p className="modal-title">Key Details</p>
          <button onClick={onClose} style={{ background: "none", border: "none", color: "var(--gray-400)", cursor: "pointer", fontSize: 18 }}>✕</button>
        </div>
        <div style={{ display: "flex", flexDirection: "column" }}>
          {rows.map(([label, val]) => (
            <div key={String(label)} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 0", borderBottom: "1px solid var(--border)", gap: 16, fontSize: 13 }}>
              <span style={{ color: "var(--gray-400)", flexShrink: 0 }}>{label}</span>
              <span style={{ textAlign: "right" }}>{val}</span>
            </div>
          ))}
        </div>
        <button className="btn btn-ghost" style={{ width: "100%", marginTop: 20 }} onClick={onClose}>Close</button>
      </div>
    </div>
  );
}

function KeysTab() {
  const [keys, setKeys] = useState<Record<string, KeyRecord>>({});
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [editKey, setEditKey] = useState<string | null>(null);
  const [viewKey, setViewKey] = useState<string | null>(null);
  const [confirm, setConfirm] = useState<{ msg: string; action: () => void } | null>(null);
  const [toast, setToast] = useState("");
  const showToast = (m: string) => { setToast(m); setTimeout(() => setToast(""), 2500); };
  const load = () => {
    setLoading(true);
    fetch("/api/owner/keys", { credentials: "include" }).then(r => r.json()).then(setKeys).finally(() => setLoading(false));
  };
  useEffect(load, []);
  const deleteKey = (k: string) => setConfirm({ msg: `Delete key ${k}? This cannot be undone.`, action: async () => { await fetch(`/api/owner/keys/${k}`, { method: "DELETE", credentials: "include" }); showToast("Key deleted."); load(); } });
  const resetHwid = async (k: string) => { await fetch(`/api/owner/keys/${k}/hwid-reset`, { method: "POST", credentials: "include" }); showToast("HWID reset."); load(); };
  const saveKey = async (k: string, updates: Partial<KeyRecord>) => { await fetch(`/api/owner/keys/${k}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(updates) }); showToast("Saved."); load(); };
  const filtered = (Object.entries(keys) as [string, KeyRecord][]).filter(([k, r]) => k.toLowerCase().includes(search.toLowerCase()) || (r.username ?? "").toLowerCase().includes(search.toLowerCase()));
  return (
    <div className="owner-tab">
      {toast && <div className="owner-toast">{toast}</div>}
      {confirm && <Confirm msg={confirm.msg} onYes={() => { confirm.action(); setConfirm(null); }} onNo={() => setConfirm(null)} />}
      {editKey && keys[editKey] && <EditKeyModal keyId={editKey} rec={keys[editKey]} onClose={() => setEditKey(null)} onSave={saveKey} />}
      {viewKey && keys[viewKey] && <KeyViewModal keyId={viewKey} rec={keys[viewKey]} onClose={() => setViewKey(null)} />}
      <div className="owner-tab-header"><h2>Key Management</h2><span className="tag tag-dim">{Object.keys(keys).length} keys</span></div>
      <input className="owner-search" placeholder="Search by key or username…" value={search} onChange={e => setSearch(e.target.value)} />
      {loading ? <div className="owner-loading"><div className="dash-spinner" /></div> : (
        <div className="keys-table-wrap">
          <table className="keys-table">
            <thead><tr><th>Key</th><th>Username</th><th>Duration</th><th>Status</th><th>HWID</th><th>Registered</th><th>Actions</th></tr></thead>
            <tbody>
              {filtered.length === 0 && <tr><td colSpan={7} className="keys-empty">No keys found.</td></tr>}
              {filtered.map(([k, r]) => (
                <tr key={k}>
                  <td><code className="key-code">{k}</code></td>
                  <td style={{ color: r.username ? "var(--white)" : "var(--gray-600)" }}>{r.username ?? "—"}</td>
                  <td style={{ color: "var(--gray-400)" }}>{r.duration}</td>
                  <td><span className={`tag ${r.disabled ? "tag-red" : "tag-white"}`}>{r.disabled ? "Disabled" : "Active"}</span></td>
                  <td>{r.hwid ? <Spoiler value={r.hwid.slice(0, 12) + "…"} /> : <span className="tag tag-dim">Unbound</span>}</td>
                  <td style={{ color: "var(--gray-600)", fontSize: 12 }}>{r.registered_at ? new Date(r.registered_at).toLocaleDateString() : "—"}</td>
                  <td><div className="key-actions">
                    <button className="btn-action" onClick={() => setViewKey(k)}>View</button>
                    <button className="btn-action" onClick={() => setEditKey(k)}>Edit</button>
                    <button className="btn-action" onClick={() => saveKey(k, { disabled: !r.disabled })}>{r.disabled ? "Enable" : "Disable"}</button>
                    <button className="btn-action" onClick={() => resetHwid(k)}>Reset HWID</button>
                    <button className="btn-action btn-action-danger" onClick={() => deleteKey(k)}>Delete</button>
                  </div></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function GenKeyTab() {
  const [duration, setDuration] = useState("lifetime");
  const [quantity, setQuantity] = useState("1");
  const [note, setNote]         = useState("");
  const [loading, setLoading]   = useState(false);
  const [result, setResult]     = useState<string[]>([]);
  const [error, setError]       = useState("");

  const seg = () => Array.from({ length: 4 }, () => "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"[Math.floor(Math.random() * 36)]).join("");

  const generate = async () => {
    const qty = Math.max(1, Math.min(25, parseInt(quantity) || 1));
    setLoading(true); setError(""); setResult([]);
    try {
      const keys: string[] = [];
      for (let i = 0; i < qty; i++) {
        const key = `FORSAKEN-${seg()}-${seg()}-${seg()}`;
        const r = await fetch("/api/owner/keys/generate", {
          method: "POST", credentials: "include",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ key, duration, note }),
        });
        if (r.ok) keys.push(key);
      }
      setResult(keys);
    } catch { setError("Failed to generate keys."); }
    finally { setLoading(false); }
  };

  return (
    <div className="owner-tab">
      <div className="owner-tab-header"><h2>Generate Keys</h2></div>
      <div style={{ maxWidth: 420 }}>
        <div className="form-group">
          <label className="form-label">Duration</label>
          <input className="form-input" value={duration} onChange={e => setDuration(e.target.value)} placeholder="e.g. lifetime, 30d, 7d" />
        </div>
        <div className="form-group">
          <label className="form-label">Quantity (1–25)</label>
          <input className="form-input" type="number" min={1} max={25} value={quantity} onChange={e => setQuantity(e.target.value)} />
        </div>
        <div className="form-group">
          <label className="form-label">Note (optional)</label>
          <input className="form-input" value={note} onChange={e => setNote(e.target.value)} placeholder="e.g. for @username, promo" />
        </div>
        {error && <p className="form-error">{error}</p>}
        <button className="btn btn-primary" disabled={loading} onClick={generate}>
          {loading ? "Generating…" : "Generate"}
        </button>
      </div>
      {result.length > 0 && (
        <div style={{ marginTop: 28 }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 }}>
            <span style={{ fontSize: 13, color: "var(--gray-400)" }}>{result.length} key{result.length > 1 ? "s" : ""} generated</span>
            <button className="btn btn-outline btn-sm" onClick={() => navigator.clipboard.writeText(result.join("\n"))}>Copy All</button>
          </div>
          <div style={{ background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "var(--radius-md)", padding: "16px", fontFamily: "monospace", fontSize: 13, display: "flex", flexDirection: "column", gap: 8 }}>
            {result.map(k => <span key={k} style={{ color: "var(--gray-200)" }}>{k}</span>)}
          </div>
        </div>
      )}
    </div>
  );
}

function DownloadTab() {
  const [input, setInput]   = useState("");
  const [saved, setSaved]   = useState(false);
  const [current, setCurrent] = useState("");
  useEffect(() => {
    fetch("/api/owner/download", { credentials: "include" }).then(r => r.json()).then(d => { setInput(d.url || ""); setCurrent(d.url || ""); });
  }, []);
  const save = async () => {
    await fetch("/api/owner/download", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: input }) });
    setCurrent(input); setSaved(true); setTimeout(() => setSaved(false), 2000);
  };
  return (
    <div className="owner-tab">
      <div className="owner-tab-header"><h2>Download Link</h2></div>
      <p className="owner-tab-sub">Set the download URL for the Forsaken <code style={{ fontFamily: "monospace" }}>.rar</code>. Customers see this via <code style={{ fontFamily: "monospace" }}>/download</code> and the dashboard.</p>
      {current && <p style={{ fontSize: 12, color: "var(--gray-600)", marginBottom: 16 }}>Current: {current}</p>}
      <div className="form-group" style={{ maxWidth: 480 }}>
        <label className="form-label">URL</label>
        <input className="form-input" value={input} onChange={e => setInput(e.target.value)} placeholder="https://example.com/forsaken.rar" />
      </div>
      <button className="btn btn-primary" onClick={save}>{saved ? "Saved" : "Update Link"}</button>
    </div>
  );
}

function AnalyticsTab() {
  const [keys, setKeys] = useState<Record<string, KeyRecord>>({});
  useEffect(() => { fetch("/api/owner/keys", { credentials: "include" }).then(r => r.json()).then(setKeys); }, []);
  const vals = Object.values(keys) as KeyRecord[];
  const stats = [
    ["Total Keys",    vals.length],
    ["Claimed",       vals.filter(r => r.claimed_by_discord !== null).length],
    ["Active (HWID)", vals.filter(r => r.hwid !== null).length],
    ["Disabled",      vals.filter(r => r.disabled).length],
    ["Unclaimed",     vals.filter(r => r.claimed_by_discord === null).length],
  ];
  return (
    <div className="owner-tab">
      <div className="owner-tab-header"><h2>Analytics</h2></div>
      <div className="analytics-grid">
        {stats.map(([l, v]) => (
          <div key={String(l)} className="analytics-card">
            <span className="analytics-value">{v}</span>
            <span className="analytics-label">{l}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function DangerTab() {
  const [inputs, setInputs]   = useState(["", "", ""]);
  const [unlocked, setUnlocked] = useState(false);
  const [error, setError]     = useState("");
  const [owners, setOwners]   = useState<{ hardcoded: string[]; extra: number[] }>({ hardcoded: [], extra: [] });
  const [newId, setNewId]     = useState("");
  const [toast, setToast]     = useState("");
  const showToast = (m: string) => { setToast(m); setTimeout(() => setToast(""), 2500); };
  const verify = async () => {
    setError("");
    const r = await fetch("/api/owner/danger/verify", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ keys: inputs }) });
    const d = await r.json();
    if (d.ok) { setUnlocked(true); fetch("/api/owner/danger/owners", { credentials: "include" }).then(r => r.json()).then(setOwners); }
    else setError("One or more keys are incorrect.");
  };
  const addOwner = async () => {
    if (!newId.trim()) return;
    await fetch("/api/owner/danger/owners", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: newId.trim() }) });
    showToast("Owner added."); setNewId("");
    fetch("/api/owner/danger/owners", { credentials: "include" }).then(r => r.json()).then(setOwners);
  };
  const removeOwner = async (id: number) => {
    await fetch(`/api/owner/danger/owners/${id}`, { method: "DELETE", credentials: "include" });
    showToast("Owner removed.");
    fetch("/api/owner/danger/owners", { credentials: "include" }).then(r => r.json()).then(setOwners);
  };
  if (!unlocked) return (
    <div className="owner-tab">
      <div className="owner-tab-header"><h2>Danger Zone</h2><span className="tag tag-red">Restricted</span></div>
      <p className="owner-tab-sub">Enter all 3 authorization keys in order to unlock this section.</p>
      <div className="danger-keys-form">
        {[0, 1, 2].map(i => (
          <div key={i} className="form-group">
            <label className="form-label">Authorization Key {i + 1}</label>
            <input className="form-input" type="password" value={inputs[i]} onChange={e => { const a = [...inputs]; a[i] = e.target.value; setInputs(a); }} placeholder={`Key ${i + 1}`} />
          </div>
        ))}
        {error && <p className="form-error">{error}</p>}
        <button className="btn btn-danger" onClick={verify}>Unlock</button>
      </div>
    </div>
  );
  return (
    <div className="owner-tab">
      {toast && <div className="owner-toast">{toast}</div>}
      <div className="owner-tab-header"><h2>Danger Zone</h2><span className="tag tag-red">Unlocked</span></div>
      <div className="danger-section">
        <h3>Owner Management</h3>
        <p className="owner-tab-sub">Hardcoded owners cannot be removed.</p>
        <div className="danger-owners">
          {owners.hardcoded.map(id => (<div key={id} className="danger-owner-row"><code>{id}</code><span className="tag tag-dim">Hardcoded</span></div>))}
          {owners.extra.map(id => (<div key={id} className="danger-owner-row"><code>{id}</code><button className="btn btn-danger btn-sm" onClick={() => removeOwner(id)}>Remove</button></div>))}
        </div>
        <div className="danger-add-owner">
          <input value={newId} onChange={e => setNewId(e.target.value)} placeholder="Discord User ID" />
          <button className="btn btn-primary" onClick={addOwner}>Add Owner</button>
        </div>
      </div>
    </div>
  );
}

export default function OwnerPage() {
  const [authed, setAuthed] = useState<boolean | null>(null);
  const [tab, setTab]       = useState<Tab>("keys");

  useEffect(() => {
    fetch("/api/auth/me", { credentials: "include" })
      .then(r => r.json()).then(d => setAuthed(d?.type === "owner")).catch(() => setAuthed(false));
  }, []);

  const logout = async () => {
    await fetch("/api/auth/logout", { method: "POST", credentials: "include" });
    setAuthed(false);
  };

  if (authed === null) return <div className="dash-loading"><div className="dash-spinner" /></div>;

  if (!authed) return (
    <div className="owner-login">
      <div className="owner-login-card card">
        <div className="owner-login-logo">
          <svg width="18" height="18" viewBox="0 0 20 20" fill="none">
            <rect x="1" y="1" width="18" height="18" stroke="white" strokeWidth="1"/>
            <line x1="1" y1="10" x2="19" y2="10" stroke="white" strokeWidth="1"/>
            <line x1="10" y1="1" x2="10" y2="19" stroke="white" strokeWidth="1"/>
          </svg>
          <span>FORSAKEN</span>
        </div>
        <h2>Owner Panel</h2>
        <p>Sign in with Discord to continue. Only authorized accounts may access this panel.</p>
        <button className="btn btn-primary owner-discord-btn" onClick={() => window.location.href = "/api/auth/discord"}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
            <path d="M20.317 4.37a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.21.375-.444.864-.608 1.25a18.27 18.27 0 0 0-5.487 0 12.64 12.64 0 0 0-.617-1.25.077.077 0 0 0-.079-.037A19.736 19.736 0 0 0 3.677 4.37a.07.07 0 0 0-.032.027C.533 9.046-.32 13.58.099 18.057a.082.082 0 0 0 .031.057 19.9 19.9 0 0 0 5.993 3.03.078.078 0 0 0 .084-.028c.462-.63.874-1.295 1.226-1.994a.076.076 0 0 0-.041-.106 13.107 13.107 0 0 1-1.872-.892.077.077 0 0 1-.008-.128 10.2 10.2 0 0 0 .372-.292.074.074 0 0 1 .077-.01c3.928 1.793 8.18 1.793 12.062 0a.074.074 0 0 1 .078.01c.12.098.246.198.373.292a.077.077 0 0 1-.006.127 12.299 12.299 0 0 1-1.873.892.077.077 0 0 0-.041.107c.36.698.772 1.362 1.225 1.993a.076.076 0 0 0 .084.028 19.839 19.839 0 0 0 6.002-3.03.077.077 0 0 0 .032-.054c.5-5.177-.838-9.674-3.549-13.66a.061.061 0 0 0-.031-.03z"/>
          </svg>
          Continue with Discord
        </button>
      </div>
    </div>
  );

  const TABS: { id: Tab; label: string }[] = [
    { id: "keys",      label: "Key Management" },
    { id: "genkey",    label: "Generate Keys"  },
    { id: "download",  label: "Download"       },
    { id: "analytics", label: "Analytics"      },
    { id: "danger",    label: "Danger Zone"    },
  ];

  return (
    <div className="owner-page">
      <aside className="owner-sidebar">
        <div className="owner-sidebar-logo">
          <svg width="14" height="14" viewBox="0 0 20 20" fill="none">
            <rect x="1" y="1" width="18" height="18" stroke="white" strokeOpacity="0.5" strokeWidth="1"/>
            <line x1="1" y1="10" x2="19" y2="10" stroke="white" strokeOpacity="0.5" strokeWidth="1"/>
            <line x1="10" y1="1" x2="10" y2="19" stroke="white" strokeOpacity="0.5" strokeWidth="1"/>
          </svg>
          FORSAKEN
        </div>
        <nav className="owner-nav">
          {TABS.map(t => (
            <button key={t.id}
              className={`owner-nav-btn ${tab === t.id ? "active" : ""} ${t.id === "danger" ? "danger" : ""}`}
              onClick={() => setTab(t.id)}>
              {t.label}
            </button>
          ))}
        </nav>
        <button className="btn btn-outline btn-sm owner-logout" onClick={logout}>Sign Out</button>
      </aside>
      <main className="owner-main">
        {tab === "keys"      && <KeysTab />}
        {tab === "genkey"    && <GenKeyTab />}
        {tab === "download"  && <DownloadTab />}
        {tab === "analytics" && <AnalyticsTab />}
        {tab === "danger"    && <DangerTab />}
      </main>
    </div>
  );
}
